### ISSUE TITLE
Incorrect Ordinator in Mourning armor pieces have the Ordinator script

### ISSUE THREAD

**Issue by DevvvvvShah** [TD-Addon/TD_Addon#114]
The following pieces shouldn't have the script OrdinatorUniform attached to them

-T_De_Necrom_Boots_01
-T_De_Necrom_GauntletL_01
-T_De_Necrom_GauntletR_01
-T_De_Necrom_Greaves_01
-T_De_Necrom_PauldronL_01
-T_De_Necrom_PauldronR_01
-T_De_Necrom_Shield_01

Orginially posted in the bugtracker by Vern, they still have the script and didn't see the issue here currently.

**Comment by jamrt** [comment]
Unfortunately, I cannot find a reason, either on the forums or on Discord, why that script should be removed.

They are an ordinator uniform, same as the vanilla Indoril one.

**Comment by jamrt** [comment]
Okay, have been informed that this is because in Morrowind.esm and Tribunal.esm only the helmet and cuirass of the various Ordinators actually have this script attached.

After checking PfP and some of the more recent MPP/UMP versions, it looks like nobody ever changed this, so I removed the scripts from our non-cuirass and non-helmet armor bits as well.
