### ISSUE TITLE
Necrom bonewalkers have the same OpenMW resizing bug that Kobolds used to have

### ISSUE THREAD

**Issue by sultan-of-rum** [TD-Addon/TD_Addon#437]
Necrom bonewalkers randomly resize in OpenMW. Same issue that Kobolds (used to) have.

Something to do with scale not being properly applied prior to animation?

![image](https://github.com/TD-Addon/TD_Addon/assets/87770191/44772051-ea41-46f7-af68-61010c1dfee4)

**Comment by RonikTR** [comment]
This has now been fixed in the latest OpenMW build.

There's another issue with the asset that was discovered during the investigation of the issue related to its bounding box, though. It doesn't have a huge functional impact, but it's easy to fix: https://www.tamriel-rebuilt.org/asset/necrom-procession-bonewalker-bounding-box-fix

**Comment by Kynesifnar** [comment]
The animated .nif files used by the construction set aren't used by Morrowind at all. Only the x_.nif and x_.kf files are.
