### ISSUE TITLE
SH Set (sandy) asset caspers 

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#484]
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/b6360002-abf7-4d67-ade4-413dbeed1921)
T_Mw_CaveSH_Curve_03 - caspers. Also caspers when gridsnapped to T_Mw_CaveSH_Hall_02

**Comment by Aveno2** [comment]
and more 
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/9e80563c-c8b8-487a-a6d8-a98bae7c0b1b)
T_Mw_CaveSH_3way_01. seams when connecting with T_Mw_CaveSH_Corner_01

**Comment by Snailsting** [comment]
There is also a seam when tr_in_shcave_room_07.nif connects to another piece on one side
![Room07](https://github.com/TD-Addon/TD_Addon/assets/120365872/48607853-1b2f-44c1-b39a-9303e1376e52)

And the floor of tr_in_shcave_r_cor_03.nif doesn't line up with any of the other room pieces
![cor](https://github.com/TD-Addon/TD_Addon/assets/120365872/4a0e5b5e-2d9f-4455-8229-444797ef4427)

Though both those issues have been present since those pieces where made, it's nothing recent

**Comment by antonisauren** [comment]
Should be fixed in https://www.tamriel-rebuilt.org/sites/default/files/assets/Shipal-Shin%20cave%20set_5.7z

**Comment by JackimoffWackimoff** [comment]
Uploaded fixed meshes ONLY from the above claim. The rest of that claim is still in review.
