### ISSUE TITLE
Imperial highway markers are too faded

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#508]
The colors on the T_Imp_HighwayMStone markers are extremely washed out and almost imperceptible. The Color Roads are well maintained, and these markers should be clearly visible to the player. It would also be nice to make them activators which display the name of the color road being marked.

**Comment by Snailsting** [comment]
Reposting some additional stuff from Discord here so it doesn't get lost

- Markers for the Purple Road will also need to be made (Both standard and mossy versions)
- And all Black variants can be deprecated since we dropped TES IV's Orange Road and reused the color for its Black Road


Also, as a sidenote this is the same issue as https://github.com/TD-Addon/TD_Addon/issues/471

**Comment by hemaris-tr** [comment]
I just pushed a fix for the Gold Road milestone assets only, to ensure that they're in before the AS release. The rest of the roads will be covered by [this asset contribution](https://www.tamriel-rebuilt.org/asset/edits-imperial-highway-milestones), once it's reviewed.

They still all need to be converted from statics to activators.
