### ISSUE TITLE
"Off" Colovian lanterns cast light

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#516]
All of the following lanterns cast 128 radius light, but should cast 0 light.

T_Imp_Var_ColLantern02_off
T_Imp_Var_ColLantern03_off
T_Imp_Var_ColLantern04_off
T_Imp_Var_ColLantern05_off

**Comment by Snailsting** [comment]
No, they are working as intended

Light sources that the player can pick up need a normal radius so that they can actually be used when equipped
They have "Off by default" ticked so they don't actually emit light in-game unless they are equipped by the player or an NPC
It's just the CS that displays those lights as if they were on anyway
