### ISSUE TITLE
T_Mw_Und_BoneldGr_01 doesn't seem to cast spells

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#626]
has spell list & adequate magicka yet won't cast spells (testing on openmw)

**Comment by Kynesifnar** [comment]
I haven't seen any such problems with them in my current playthrough that is not on OpenMW.

**Comment by Aveno2** [comment]
yep quick test on vanilla (w/ mwse) there's no issue
some kind of openMW problem

**Comment by Aveno2** [comment]
although on vanilla engine testing it refuses to engage in melee combat with me, and flees once its done casting spells

**Comment by Kynesifnar** [comment]
Hm, I don't think that I've gotten that one either.

**Comment by Snailsting** [comment]
I'm assuming that's prolly because it has a summon walking about, right?

To quote something Evil Eye said the other day:
"Unless it's a full caster, the summon should be removed. Actors without weapons that have a summon out start fleeing. And yes that applies to creatures that would do health damage using their fists (that being what makes it stupid)"

**Comment by Aveno2** [comment]
yes, but the creature does have a weapon it can use 
I find MDMD dremora lords with weapons that summon dremora don't flee with their summon so I'm not sure why the issue occurs with greater bonelords (although I've played MDMD on openMW not vanilla)

**Comment by Aveno2** [comment]
darn ofc
