### ISSUE TITLE
T_Cyr_Flora_Lilypad_0X have black spots

### ISSUE THREAD

**Issue by MinerMan60101** [TD-Addon/TD_Addon#668]
`pc\f\pc_flora_lilipad_01.nif` et al have a streak of black on their pads, owing to bad UVs. Some sort of group for these lilypads would also be nice.

**Comment by Snailsting** [comment]
The UVs aren't the problem, it suffers from the same issue as the Nirnroot plant did

For the uninitiated, the game prioritizes textures in the main "Textures" folder over those in its subfolders despite what the file path in the .nif is
So if it finds a texture called "pc_flora_lilypad_01.dds" in there it will just use that one instead of using "textures\pc\env\pc_flora_lilypad_01.dds" like it should in this case

**Comment by antonisauren** [comment]
Is that texture removed from data and just leftover in last year release?

**Comment by Snailsting** [comment]
They're still in TamrielDataMain at the moment
The old individual textures were left where they were when the lilypads got updated to use an atlased version of them

**Comment by revenorror** [comment]
I atlased the lilypads so technically I caused this but that means I know how to fix it 
Snailsting's explanation is correct, the fix for this would just be deleting the old textures from the repository. But, I know before my hiatus there was some talk floating around about flora missing textures. I would continuously trace these back to a mini-project I was doing to atlas flora (and deleting the old versions of the files as I went + moving them into a subfolder to try and get files out of the main folder). I suspect the T_D meshes were being overridden by patches like the one from [Graphic Herbalism](https://www.nexusmods.com/morrowind/mods/46599) (which is now COMPLETELY outdated and unnecessary - can someone contact Stuporstar to have it removed?) or potentially other high poly mesh replacers. To fix this someone added these files back in causing the duplicate file/wrong UV bug or some of these files werent removed from some people's installs. The most proper solution would be deleting the files from the repo and keeping the new textures where they are but if we don't want to deal with people complaining we could also just edit the mesh file paths to use the files from the main folder + relocate the new texture to the main folder (now that T_D has moved to the loose files over BSA choosing the former option would not necessarily fix the bug on all people's systems, moving the new file to the main folder is most likely to work). Minimizing the number of textures in the main texture folder may only be a thing that I care about but man it is annoying. I would love there to be a final killer refactor for PC/sky bvvvvvvvv 
Mostly just typing this all up so you all are aware this is an issue that has been happening and why. Also happened to the Nirnroot, etcetc
