### ISSUE TITLE
The HD versions of the Nirnroot textures weren't renamed

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#671]
Sorry for not catching this earlier, but https://www.tamriel-rebuilt.org/asset/nirnroot-textures-fix ended up only renaming the SD textures

The HD versions of `pc\env\pc_tx_nirn_leaf_01.dds` & `pc\env\pc_tx_nirn_leaf_02.dds` still need to be renamed to `pc\env\pc_tx_nirnroot_01.dds` & `pc\env\pc_tx_nirnroot_02.dds`

**Comment by Feighten** [comment]
[Nirnroot Texture Fix HD.zip](https://github.com/user-attachments/files/16756462/Nirnroot.Texture.Fix.HD.zip)
Here is an HD-only version of the same file package to fill in the gaps I forgot. I don't think the structure is correct for HD because I'm not used to working with it, but the textures included are HD.
