### ISSUE TITLE
T_Mw_CaveSH_NS_R_Cen_02 duplicate of room corner

### ISSUE THREAD

**Issue by MinerMan60101** [TD-Addon/TD_Addon#678]
`tr\i\tr_in_shc_ns_r_cen_02.nif` is a duplicate of the corner piece rather than being a 2x2 room piece as is the case in the sand set version. Should be easy to recreate thankfully, based on `tr\i\tr_in_shc_ns_r_cen_01.nif`.

**Comment by Snailsting** [comment]
The correct version already exists, but it looks like it was accidentally overwritten with that corner piece in https://github.com/TD-Addon/TD_Addon/commit/d0462916b7636bef9105545fefd7babd45826118

The normals on that earlier model wouldn't be seamless with the rest of the set though
So instead of simply reverting it, it might be worth checking with Stele first to see if he still has the correct tweaked version
