### ISSUE TITLE
BookArt map textures need to be packaged loose

### ISSUE THREAD

**Issue by charger24** [TD-Addon/TD_Addon#92]
Several people have reported problems with BookArt textures on the maps not showing up ingame. I have been able to replicate this error on both vanilla and OpenMW, though there doesn't seem to be any pattern to which ones work when packaged into the .bsa and which don't. The only sure way I've found to solve the problem is the have the BookArt files loose in the install folder.

**Comment by Assumeru** [comment]
Do we have a list of those? Because I can explain at least two.

`T_Sc_MapReachSHOTN` uses `Sky/Skyrim_TheReach_Bookmap.dds` which should be `Sky\Skyrim_TheReach_Bookmap.dds`. (Note the slash.)
`T_Sc_GuideToAnvilPC` uses `pc\anvil_region_map.dds` but the file is called `pc\pc_anvil_region_map.dds` in my BSA. (Which may or may not be a little out of date.)

**Comment by jamrt** [comment]
I can confirm from personal experience that Morrowind can deal with slashes instead of backslashes _only_ with loose files, and this would produce exactly this effect. This behavior is _not_ limited to bookart, I first encountered it with Lyithdonea meshes that would display their textures correctly when loose and didn't work when packaged in a BSA. 

I corrected the two paths and called it a day.
